# Generated by Django 6.0.2 on 2026-03-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='type',
            field=models.CharField(choices=[('payment', 'Payement'), ('login', 'Login'), ('verification', 'Verification')], max_length=50),
        ),
    ]
