# Generated by Django 6.0.2 on 2026-03-10 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MobileCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('beeline', 'Beeline'), ('ucell', 'Ucell'), ('uzmobile', 'UzMobile'), ('mobiuz', 'MobiUz'), ('humans', 'Humans')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('operator_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=4)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tarif_nomi', models.CharField(blank=True, max_length=250, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymenttype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.status')),
            ],
        ),
        migrations.CreateModel(
            name='InternetPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('uztelecom', 'Uztelecom'), ('sarkor telecom', 'Sarkor Telecom'), ('turon telecom', 'Turon Telecom'), ('tps', 'TPS'), ('sharq telecom', 'Sharq Telecom'), ('comnet', 'Comnet'), ('east telecom', 'East Telecom'), ('iplus', 'IPLUS'), ('nano telecom', 'Nano Telecom'), ('free link', 'Free link')], max_length=250)),
                ('provider_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=4)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymenttype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.status')),
            ],
        ),
        migrations.CreateModel(
            name='CommunalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('hududgaz', 'Hududgaz'), ('regional electric networks', 'Regional Electric Networks(RES)'), ("suvta'minot", "Suvta'minot"), ('toza hudud', 'Toza Hudud'), ("issiqlik ta'minoti", "Issiqlik ta'minoti")], max_length=250)),
                ('provider_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('service_type', models.CharField(choices=[('elektr energiyasi', 'Elektr Energiyasi'), ('ichimlik suvi', 'Ichimlik Suvi'), ('tabiiy gaz', 'Tabiiy Gaz'), ('issiqlik energiyasi', 'Issiqlik Energiyasi'), ('kanalizatsiya', 'Kanalizatsiya'), ('chiqindi', 'Chiqindi')], max_length=50)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymenttype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.status')),
            ],
        ),
    ]
